DROP DATABASE IF EXISTS chirpy;
CREATE DATABASE chirpy;
USE chirpy;

CREATE TABLE `chirps` (
  -- TABLE CODE TO GO HERE
  id INT AUTO_INCREMENT PRIMARY KEY,
  author VARCHAR(100),
  chirp VARCHAR(250),
  time_created TIMESTAMP
);